import { useState, useMemo } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import Layout from '../../components/layout/Layout';
import api from '../../api/client';
import OpsNavBar from './OpsNavBar';

export default function OrdersMgmt() {
  const queryClient = useQueryClient();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isAutoGenerateModalOpen, setIsAutoGenerateModalOpen] = useState(false);
  const [autoGenerateDate, setAutoGenerateDate] = useState(new Date().toISOString().split('T')[0]);
  const [orderForm, setOrderForm] = useState({ customer_id: '', daily_menu_id: '', count: 1, date: new Date().toISOString().split('T')[0] });
  const [expandedGroups, setExpandedGroups] = useState({});
  const [activeTab, setActiveTab] = useState('active');

  const { data: orders, isLoading } = useQuery({ queryKey: ['orders'], queryFn: () => api.get('/operations/orders').then(res => res.data) });
  const { data: customers } = useQuery({ queryKey: ['customers'], queryFn: () => api.get('/crm/customers').then(res => res.data) });
  const { data: dailyMenus } = useQuery({ queryKey: ['daily-menus'], queryFn: () => api.get('/operations/daily-menus').then(res => res.data) });

  const createOrderMutation = useMutation({
    mutationFn: (data) => api.post('/operations/orders', data),
    onSuccess: () => {
      queryClient.invalidateQueries(['orders']);
      toast.success('Order created successfully');
      setIsModalOpen(false);
      setOrderForm({ customer_id: '', daily_menu_id: '', count: 1, date: new Date().toISOString().split('T')[0] });
    },
    onError: (err) => toast.error(err.response?.data?.error || 'Failed to create order')
  });

  const autoGenerateMutation = useMutation({
    mutationFn: (date) => api.post('/operations/orders/auto-generate', { date }),
    onSuccess: (res) => {
      queryClient.invalidateQueries(['orders']);
      if (res.data.generatedCount > 0) {
        toast.success(`Successfully generated ${res.data.generatedCount} orders!`);
      } else {
        toast.error(res.data.message || 'No orders generated (perhaps no active packages or duplicate prevention).');
      }
      setIsAutoGenerateModalOpen(false);
    },
    onError: (err) => toast.error(err.response?.data?.error || 'Failed to auto-generate orders')
  });

  const statusMutation = useMutation({
    mutationFn: ({ id, delivery_status }) => api.put(`/operations/orders/${id}/status`, { delivery_status }),
    onSuccess: () => {
      queryClient.invalidateQueries(['orders']);
      toast.success('Order status updated');
    },
    onError: (err) => toast.error(err.response?.data?.error || 'Failed to update order status')
  });

  const batchStatusMutation = useMutation({
    mutationFn: ({ order_ids, delivery_status }) => api.put(`/operations/orders/batch-status`, { order_ids, delivery_status }),
    onSuccess: () => {
      queryClient.invalidateQueries(['orders']);
      toast.success('Orders status updated');
    },
    onError: (err) => toast.error(err.response?.data?.error || 'Failed to update order status')
  });

  const getStatusColor = (status) => {
    switch(status) {
      case 'DELIVERED': return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20';
      case 'PENDING': return 'bg-amber-500/10 text-amber-400 border-amber-500/20';
      case 'CANCELLED': return 'bg-rose-500/10 text-rose-400 border-rose-500/20';
      default: return 'bg-white/5 text-slate-300 border-white/10';
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    createOrderMutation.mutate(orderForm);
  };

  const groupedOrders = useMemo(() => {
    if (!orders) return {};
    const groups = {}; // Date -> { date, totalQty, deliveredQty, customers: { customerName -> { name, address, orders: [] } } }
    
    orders.forEach(order => {
      const date = order.date;
      const customerName = order.customer?.full_name || 'Unknown';
      
      if (!groups[date]) {
        groups[date] = { date, totalQty: 0, deliveredQty: 0, customers: {} };
      }
      
      if (!groups[date].customers[customerName]) {
        groups[date].customers[customerName] = {
           name: customerName,
           address: order.customer?.delivery_address,
           orders: []
        };
      }
      
      groups[date].customers[customerName].orders.push(order);
      groups[date].totalQty += order.count;
      if (order.delivery_status === 'DELIVERED') groups[date].deliveredQty += order.count;
    });
    
    return groups;
  }, [orders]);

  const toggleGroup = (key) => {
    setExpandedGroups(prev => ({ ...prev, [key]: prev[key] === undefined ? false : !prev[key] }));
  };

  return (
    <Layout title="Operations Hub" subtitle="Manage customer meal orders and deliveries">
      <OpsNavBar />
      
      <div className="flex justify-between items-center mb-6">
        <div className="flex bg-surface-800 p-1 rounded-xl border border-white/5">
          <button onClick={() => setActiveTab('active')} className={`px-6 py-2.5 rounded-lg font-bold text-sm transition-all ${activeTab === 'active' ? 'bg-fuchsia-600 text-white shadow-lg' : 'text-slate-400 hover:text-white'}`}>Active Deliveries</button>
          <button onClick={() => setActiveTab('history')} className={`px-6 py-2.5 rounded-lg font-bold text-sm transition-all ${activeTab === 'history' ? 'bg-surface-700 text-white shadow-lg border border-white/10' : 'text-slate-400 hover:text-white'}`}>Delivery History</button>
        </div>
        <div className="flex gap-4">
          <button onClick={() => setIsAutoGenerateModalOpen(true)} className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl shadow-lg transition-all flex items-center gap-2">
            <span>⚡ Auto Generate</span>
          </button>
          <button onClick={() => setIsModalOpen(true)} className="px-5 py-2.5 bg-fuchsia-600 hover:bg-fuchsia-500 text-white font-bold rounded-xl shadow-lg shadow-fuchsia-500/20 transition-all">
            + Add New Order
          </button>
        </div>
      </div>

      <div className="space-y-4">
        {isLoading ? (
          <div className="bg-surface-800 rounded-2xl border border-white/5 p-8 text-center text-slate-500">Loading orders...</div>
        ) : !orders || orders.length === 0 ? (
          <div className="bg-surface-800 rounded-2xl border border-white/5 p-8 text-center text-slate-500">No orders found.</div>
        ) : (
          (() => {
            const filteredGroups = Object.entries(groupedOrders).filter(([date, group]) => {
              if (activeTab === 'active') return group.deliveredQty < group.totalQty;
              return group.deliveredQty === group.totalQty && group.totalQty > 0;
            });
            
            if (filteredGroups.length === 0) {
               return <div className="bg-surface-800 rounded-2xl border border-white/5 p-8 text-center text-slate-500">No {activeTab} orders found.</div>;
            }
            
            return filteredGroups.map(([date, group]) => {
              const isOpen = expandedGroups[date] !== false; 
            
            return (
              <div key={date} className="bg-surface-800 rounded-2xl border border-white/5 overflow-hidden transition-all">
                {/* Accordion Header */}
                <button 
                  onClick={() => toggleGroup(date)}
                  className="w-full px-6 py-4 flex items-center justify-between bg-surface-900/30 hover:bg-surface-900/50 transition-colors border-b border-white/5"
                >
                  <div className="flex items-center gap-4">
                    <span className={`text-xl transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`}>
                      🔽
                    </span>
                    <h3 className="text-lg font-bold text-white">
                      {date} <span className="text-slate-400 font-normal">({Object.keys(group.customers).length} Customers)</span>
                    </h3>
                  </div>
                  <div className="flex items-center gap-6">
                    <div className="text-right">
                      <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">Delivered</p>
                      <p className="text-sm font-bold text-emerald-400">{group.deliveredQty} <span className="text-slate-500">/ {group.totalQty}</span></p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">Total Qty</p>
                      <p className="text-lg font-bold text-white">{group.totalQty} <span className="text-sm font-normal text-slate-400">meals</span></p>
                    </div>
                  </div>
                </button>

                {/* Accordion Body */}
                {isOpen && (
                  <div className="divide-y divide-white/5">
                    {Object.values(group.customers).map(customer => {
                      const customerKey = `${date}-${customer.name}`;
                      const isCustomerOpen = expandedGroups[customerKey] !== false; // Default open
                      return (
                      <div key={customer.name} className="hover:bg-white/[0.02] transition-colors">
                        <div className="w-full px-6 py-4 flex items-center justify-between group">
                          <div className="flex items-center gap-3 cursor-pointer flex-1" onClick={() => toggleGroup(customerKey)}>
                            <span className={`text-sm text-slate-400 transition-transform duration-200 ${isCustomerOpen ? 'rotate-90' : ''}`}>
                              ▶
                            </span>
                            <div>
                              <p className="font-bold text-white text-md group-hover:text-fuchsia-300 transition-colors">👤 {customer.name}</p>
                              <p className="text-xs text-slate-400 mt-1">{customer.address || 'No delivery address provided'}</p>
                            </div>
                          </div>
                          
                          <div className="flex items-center gap-4">
                            <div className="text-xs font-bold text-slate-500 bg-surface-900 px-3 py-1 rounded-full border border-white/5">
                              {customer.orders.length} orders
                            </div>
                            
                            {customer.orders.some(o => o.delivery_status !== 'DELIVERED') ? (
                              <button 
                                onClick={(e) => { 
                                  e.stopPropagation();
                                  if(window.confirm('Mark ALL orders for this customer as DELIVERED?')) {
                                    const pendingIds = customer.orders.filter(o => o.delivery_status !== 'DELIVERED').map(o => o.id);
                                    batchStatusMutation.mutate({ order_ids: pendingIds, delivery_status: 'DELIVERED' });
                                  }
                                }} 
                                className="px-4 py-2 bg-emerald-600/20 hover:bg-emerald-600 text-emerald-400 hover:text-white text-xs font-bold rounded-lg transition-colors border border-emerald-500/20 shadow-lg whitespace-nowrap"
                              >
                                Mark All Delivered
                              </button>
                            ) : (
                              <span className="px-4 py-2 bg-white/5 text-emerald-500 text-xs font-bold rounded-lg border border-white/5 uppercase tracking-widest flex items-center gap-2 whitespace-nowrap">
                                ✅ Delivered
                              </span>
                            )}
                          </div>
                        </div>
                        
                        {isCustomerOpen && (
                          <div className="px-6 pb-4 ml-8 space-y-2">
                            {customer.orders.map(order => (
                              <div key={order.id} className="flex items-center justify-between bg-surface-900/50 rounded-lg p-3 border border-white/5">
                                <div className="flex items-center gap-4">
                                  <span className="text-sm font-bold text-fuchsia-400 w-16">{order.daily_menus?.meal_type}</span>
                                  <span className="text-sm font-bold text-white">x{order.count}</span>
                                  <span className={`px-2 py-0.5 text-[10px] font-bold uppercase tracking-widest rounded-full border ${getStatusColor(order.delivery_status)}`}>
                                    {order.delivery_status}
                                  </span>
                                </div>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    )})}
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>

      {/* Add Order Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
          <div className="bg-surface-800 w-full max-w-md rounded-2xl border border-white/10 shadow-2xl p-6">
            <h3 className="text-xl font-bold text-white mb-6">Create Customer Order</h3>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-400 mb-2">Customer</label>
                <select required value={orderForm.customer_id} onChange={e => setOrderForm({...orderForm, customer_id: e.target.value})} className="w-full bg-surface-900 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-fuchsia-500">
                  <option value="">-- Select Customer --</option>
                  {customers?.map(c => <option key={c.id} value={c.id}>{c.full_name} ({c.phone})</option>)}
                </select>
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-400 mb-2">Delivery Date</label>
                <input required type="date" value={orderForm.date} onChange={e => setOrderForm({...orderForm, date: e.target.value})} className="w-full bg-surface-900 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-fuchsia-500" />
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-400 mb-2">Daily Menu (Meal Plan)</label>
                <select required value={orderForm.daily_menu_id} onChange={e => setOrderForm({...orderForm, daily_menu_id: e.target.value})} className="w-full bg-surface-900 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-fuchsia-500">
                  <option value="">-- Select Planned Menu --</option>
                  {dailyMenus?.map(dm => <option key={dm.id} value={dm.id}>{dm.date} - {dm.meal_type}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-xs font-bold text-slate-400 mb-2">Quantity (Meals)</label>
                <input required type="number" min="1" value={orderForm.count} onChange={e => setOrderForm({...orderForm, count: e.target.value})} className="w-full bg-surface-900 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-fuchsia-500" />
              </div>
              <div className="flex gap-3 pt-4">
                <button type="button" onClick={() => setIsModalOpen(false)} className="flex-1 py-3 bg-white/5 hover:bg-white/10 text-white font-bold rounded-xl transition-colors">Cancel</button>
                <button type="submit" disabled={createOrderMutation.isPending} className="flex-1 py-3 bg-fuchsia-600 hover:bg-fuchsia-500 text-white font-bold rounded-xl shadow-lg transition-all disabled:opacity-50">
                  Save Order
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Auto Generate Modal */}
      {isAutoGenerateModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
          <div className="bg-surface-800 w-full max-w-md rounded-2xl border border-white/10 shadow-2xl p-6">
            <h3 className="text-xl font-bold text-white mb-2">Auto-Generate Orders</h3>
            <p className="text-sm text-slate-400 mb-6">
              Automatically create orders by matching active customer packages with the planned Daily Menus for a specific date.
            </p>
            <form onSubmit={(e) => { e.preventDefault(); autoGenerateMutation.mutate(autoGenerateDate); }} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-400 mb-2">Target Date</label>
                <input required type="date" value={autoGenerateDate} onChange={e => setAutoGenerateDate(e.target.value)} className="w-full bg-surface-900 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-indigo-500" />
              </div>
              
              <div className="flex gap-3 pt-4">
                <button type="button" onClick={() => setIsAutoGenerateModalOpen(false)} className="flex-1 py-3 bg-white/5 hover:bg-white/10 text-white font-bold rounded-xl transition-colors">Cancel</button>
                <button type="submit" disabled={autoGenerateMutation.isPending} className="flex-1 py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl shadow-lg transition-all disabled:opacity-50 flex justify-center items-center gap-2">
                  {autoGenerateMutation.isPending ? 'Generating...' : '⚡ Generate'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </Layout>
  );
}
