-- Add multi-rider tracking columns to operations_orders table
-- Note: Since operations_orders is a view, we create a separate table for assignments

-- Create a new table to track rider assignments for the orders view
CREATE TABLE IF NOT EXISTS public.operations_delivery_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT UNIQUE,
  rider_id UUID REFERENCES public.sys_users(id) ON DELETE CASCADE,
  picked_up_at TIMESTAMP WITH TIME ZONE,
  status VARCHAR(255) DEFAULT 'ACCEPTED',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS but allow access for now
ALTER TABLE public.operations_delivery_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for operations_delivery_assignments" ON public.operations_delivery_assignments FOR ALL USING (true) WITH CHECK (true);

